[package]
name = "mpd-slack-status"
version = "0.1.0"
authors = ["Joshua Hawxwell <m@hawx.me>"]

[dependencies]
clap = "2"
toml = "0.4"
serde = "1"
serde_derive = "1"
reqwest = "0.5.1"
time = "0.1"
mpd = "*"
